### ISSUE TITLE
Program Project page

### ISSUE THREAD

**Issue by nickworks** [nickworks/megaworks#8]
Program out the front-end (HTML / CSS) of the Project page.
Refer to the HD wireframe.

**Comment by nickworks** [comment]
I ended up working on this one today. It's starting to come along nicely.

**Comment by AJSmithJohnson** [comment]
Should I find a different page to work on?

On Feb 2, 2018 7:10 PM, "Nick" <notifications@github.com> wrote:

I ended up working on this one today. It's starting to come along nicely.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/nickworks/megaworks/issues/8#issuecomment-362747682>,
or mute the thread

**Comment by nickworks** [comment]
Sure! Just grab any unclaimed issues in the issue tracker, and start programming. 😄

**Comment by AJSmithJohnson** [comment]
Ok! Thanks
